# possible task prompts:
# <CAPTION_TO_PHRASE_GROUNDING>
# <OD>
# <DENSE_REGION_CAPTION>
# <REGION_PROPOSAL>
# <CAPTION>+<CAPTION_TO_PHRASE_GROUNDING>
# <DETAILED_CAPTION>+<CAPTION_TO_PHRASE_GROUNDING>
# <MORE_DETAILED_CAPTION>+<CAPTION_TO_PHRASE_GROUNDING>
task_prompt: <CAPTION>+<CAPTION_TO_PHRASE_GROUNDING>
# text is needed only is task prompt is "<CAPTION_TO_PHRASE_GROUNDING>"
text: ""